cat > netlify.toml << EOL
[build]
  publish = "builds"
  command = "./build-all.sh"

[[redirects]]
  from = "/"
  to = "/project1"
  status = 302
  force = true

[[redirects]]
  from = "/:project/*"
  to = "/:project/:splat"
  status = 200

[[redirects]]
  from = "/:project"
  to = "/:project/"
  status = 200
EOL